import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { featuresRoot, walkFeatures } from './walk.js';
import type { FeatureIndex, FeatureIndexEntry, FeatureRow } from './types.js';

/**
 * @coodra/shared/features — INDEX.md + INDEX.json generator.
 *
 * The index is the load-bearing artefact for the skill pattern: agents
 * read it on every session start (cheap — names + descriptions only)
 * and then call `coodra__get_feature(slug)` to load a body on demand.
 *
 * Two outputs, kept in lock-step:
 *
 *   - `INDEX.md`   — human + agent fallback. Easy to skim, easy to
 *     paste into a prompt, easy to diff in git.
 *   - `INDEX.json` — machine-readable. The bridge ships it as the
 *     SessionStart context block; the MCP tools surface it directly.
 *
 * The generator is **idempotent and deterministic**:
 *   - features sort by slug
 *   - timestamps use the highest mtime across the tree (NOT `Date.now()`)
 *     so two regens with no changes produce byte-identical output and
 *     git stays clean
 *   - the only non-determinism would come from generatedAt, which we
 *     anchor to `indexerSourceMtime` rather than wall-clock time
 */

export interface GenerateIndexOptions {
  /** Project root (the directory containing `.coodra.json`). */
  readonly projectCwd: string;
  /** Project slug — written into INDEX.json's `projectSlug` field. */
  readonly projectSlug: string;
  /** When false (default), skip writing if the new content matches what's on disk. */
  readonly forceWrite?: boolean;
  /**
   * Inject a fixed clock for tests / determinism guarantees. When omitted
   * the generator uses the highest mtime across the feature tree.
   */
  readonly nowOverride?: Date;
}

export interface GenerateIndexResult {
  /** The structured index that was written. */
  readonly index: FeatureIndex;
  /** Path to INDEX.md. */
  readonly indexMdPath: string;
  /** Path to INDEX.json. */
  readonly indexJsonPath: string;
  /** True when at least one of the two index files was rewritten. */
  readonly changed: boolean;
  /** Slugs that have at least one warning — surfaced for UX. */
  readonly slugsWithWarnings: ReadonlyArray<string>;
}

/**
 * Walk `<projectCwd>/docs/features/`, generate the structured index,
 * and write `INDEX.md` + `INDEX.json` to the same directory.
 *
 * Filesystem behaviour:
 *   - Creates `docs/features/` if missing (writes only the two index
 *     files; never creates feature directories on its own).
 *   - When `forceWrite=false` (default), reads the existing index files
 *     and only re-writes those whose content has actually changed —
 *     avoids unnecessary mtime bumps that would loop the bridge's
 *     stale-index regeneration on every read.
 *
 * Returns `changed=false` only when both files exist on disk AND match
 * the freshly-generated bytes; useful for the bridge's "should I bump
 * the cache?" check.
 */
export function generateFeaturesIndex(options: GenerateIndexOptions): GenerateIndexResult {
  const root = featuresRoot(options.projectCwd);
  const indexMdPath = join(root, 'INDEX.md');
  const indexJsonPath = join(root, 'INDEX.json');

  if (!existsSync(root)) {
    mkdirSync(root, { recursive: true });
  }

  const rows = walkFeatures(options.projectCwd);
  const indexerSourceMtime = computeSourceMtime(options.projectCwd, rows);
  const generatedAt = (options.nowOverride ?? new Date(indexerSourceMtime)).toISOString();

  const entries: FeatureIndexEntry[] = rows.map(rowToIndexEntry);
  const index: FeatureIndex = {
    version: 1,
    projectSlug: options.projectSlug,
    generatedAt,
    indexerSourceMtime,
    features: entries,
  };

  const indexJsonBody = `${JSON.stringify(index, null, 2)}\n`;
  const indexMdBody = renderIndexMd(index);

  const force = options.forceWrite === true;
  const mdChanged = force || readIfExists(indexMdPath) !== indexMdBody;
  const jsonChanged = force || readIfExists(indexJsonPath) !== indexJsonBody;

  if (mdChanged) writeFileSync(indexMdPath, indexMdBody, 'utf8');
  if (jsonChanged) writeFileSync(indexJsonPath, indexJsonBody, 'utf8');

  return {
    index,
    indexMdPath,
    indexJsonPath,
    changed: mdChanged || jsonChanged,
    slugsWithWarnings: rows.filter((r) => r.warnings.length > 0).map((r) => r.slug),
  };
}

/**
 * Project the heavy `FeatureRow` view down to the lightweight index
 * entry shipped to agents.
 */
function rowToIndexEntry(row: FeatureRow): FeatureIndexEntry {
  return {
    slug: row.slug,
    name: row.frontmatter.name,
    description: row.frontmatter.description,
    whenNotToUse: row.frontmatter.whenNotToUse ?? null,
    maturity: row.frontmatter.maturity ?? 'draft',
    owners: row.frontmatter.owners ?? [],
    tags: row.frontmatter.tags ?? [],
    fileCount: row.files.length + 1, // feature.md counts
    totalBytes: row.totalBytes,
    lastUpdatedAt: row.lastUpdatedAt,
    hasWarnings: row.warnings.length > 0,
  };
}

/**
 * Highest mtime across every authored file inside `docs/features/`.
 * Numeric ms epoch. Used as `indexerSourceMtime` so the bridge can
 * cheaply detect "any feature changed since I last read the index".
 *
 * IMPORTANT: this function deliberately does NOT include the mtime of
 * `docs/features/` itself, nor of `INDEX.md` / `INDEX.json`. Why:
 * writing the index files inside the directory bumps the directory's
 * own mtime AND the index files' mtimes. If those mtimes counted,
 * every regeneration would invalidate the previous one — the second
 * `generateFeaturesIndex` call would see a different mtime than the
 * first, write a different `indexerSourceMtime`, write a different
 * INDEX.json, and report `changed=true` even when no feature changed.
 *
 * What counts: every `feature.md` + every supporting file (paths
 * already collected by `walk.ts` from `FeatureRow.files`).
 */
function computeSourceMtime(_projectCwd: string, rows: FeatureRow[]): number {
  let max = 0;
  for (const row of rows) {
    try {
      const stat = statSync(join(row.dir, 'feature.md'));
      if (stat.mtimeMs > max) max = stat.mtimeMs;
    } catch {
      // missing feature.md — already handled in walk
    }
    for (const f of row.files) {
      try {
        const stat = statSync(join(row.dir, f.path));
        if (stat.mtimeMs > max) max = stat.mtimeMs;
      } catch {
        // file disappeared between walk and stat — ignore
      }
    }
  }
  return Math.floor(max);
}

function readIfExists(path: string): string | null {
  if (!existsSync(path)) return null;
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return null;
  }
}

/**
 * Render INDEX.md from the structured index. Stable output; rendered
 * deterministically from the JSON shape so the two files always agree.
 */
export function renderIndexMd(index: FeatureIndex): string {
  if (index.features.length === 0) {
    return [
      `# Features index — ${index.projectSlug}`,
      '',
      '> Auto-generated by `coodra feature index`. Do not edit by hand —',
      '> changes are overwritten on the next regeneration.',
      '',
      `_no features yet_ · last indexed ${index.generatedAt}`,
      '',
      'Add a feature with `coodra feature add <name>` (CLI) or via the',
      `**Features** panel at \`/projects/${index.projectSlug}/features\`.`,
      '',
    ].join('\n');
  }

  const lines: string[] = [];
  lines.push(`# Features index — ${index.projectSlug}`);
  lines.push('');
  lines.push('> Auto-generated by `coodra feature index`. Do not edit by hand —');
  lines.push('> changes are overwritten on the next regeneration.');
  lines.push('');
  lines.push(`${index.features.length} feature${index.features.length === 1 ? '' : 's'} · last indexed ${index.generatedAt}`);
  lines.push('');
  for (const f of index.features) {
    lines.push(`## ${f.slug}`);
    if (f.maturity !== 'stable') {
      lines.push(`> _${f.maturity}_`);
    }
    lines.push(`**When:** ${normaliseWhitespace(f.description)}`);
    if (f.whenNotToUse !== null && f.whenNotToUse.length > 0) {
      lines.push(`**Not for:** ${normaliseWhitespace(f.whenNotToUse)}`);
    }
    if (f.tags.length > 0) {
      lines.push(`**Tags:** ${f.tags.join(', ')}`);
    }
    lines.push(`**Files:** ${f.fileCount} (${formatBytes(f.totalBytes)})`);
    lines.push(`**Last updated:** ${f.lastUpdatedAt}`);
    lines.push(`**Load via:** \`coodra__get_feature({slug:"${f.slug}"})\``);
    if (f.hasWarnings) {
      lines.push('> _has validation warnings — open in the web UI to fix_');
    }
    lines.push('');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

function normaliseWhitespace(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}
