#!/usr/bin/env node
// Read package.json's `version` field and rewrite `src/version.ts` so the bin
// always carries the published semver at runtime without a JSON.parse on cold
// start. Wired as `prebuild` in package.json — `pnpm --filter @coodra/cli
// build` regenerates the file before tsc emits it. Tests can import the same
// constant; CI fails if the committed value drifts from package.json (see
// __tests__/unit/version-sync.test.ts).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(here, '..', 'package.json');
const versionFile = join(here, '..', 'src', 'version.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const version = pkg.version;
if (typeof version !== 'string' || version.length === 0) {
  console.error(`sync-version: package.json is missing a 'version' field at ${pkgPath}`);
  process.exit(1);
}

const banner =
  '// Generated by `scripts/sync-version.mjs` (wired as `prebuild`). ' +
  'Do not edit by hand —\n// rerun `pnpm --filter @coodra/cli build` (or run the script directly) ' +
  'after\n// bumping `package.json#version`. The committed value MUST match package.json so\n' +
  '// `__tests__/unit/version-sync.test.ts` passes in CI.\n';
const body = `export const VERSION = '${version}';\n`;
writeFileSync(versionFile, banner + body, 'utf8');
console.log(`sync-version: wrote VERSION='${version}' to ${versionFile}`);
