import { access, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { WriteOutcome } from './types.js';

/**
 * Solo-mode env vars init writes — sentinels per spec §4.1 + spec §6
 * agent-human boundary. The values for `CLERK_SECRET_KEY` and
 * `CLERK_PUBLISHABLE_KEY` are sentinels that the auth chain handles via
 * the solo-bypass branch (per `system-architecture.md §19`); the
 * `LOCAL_HOOK_SECRET` is randomly generated at init time so each project
 * gets a fresh secret without the user ever pasting one.
 */
export interface BaselineEnv {
  // COODRA_MODE intentionally NOT in the project-level baseline.
  // Mode is a per-machine setting that lives in ~/.coodra/.env
  // (written by `team setup` / `team join`) — putting it in the
  // project .env would override the home setting because cwd .env
  // wins over home in `loadHomeEnv`'s precedence. See Phase 4 H6
  // verification: writing `COODRA_MODE=solo` to project .env
  // silently put team-mode users back into solo on every `start`.
  // Solo's default is read at the bridge / mcp-server boot path's
  // Zod schema (`baseEnvSchema.COODRA_MODE.default('solo')`), so
  // a missing var still yields solo for fresh users.
  readonly CLERK_SECRET_KEY: string;
  readonly CLERK_PUBLISHABLE_KEY: string;
  readonly LOCAL_HOOK_SECRET: string;
  readonly MCP_SERVER_PORT: string;
  readonly HOOKS_BRIDGE_PORT: string;
}

/** Keys init never writes — the user supplies these per `essentialsforclaude/02-agent-human-boundary.md` §2.2. */
export const FORBIDDEN_INIT_KEYS = [
  'ANTHROPIC_API_KEY',
  'GOOGLE_API_KEY',
  'OPENAI_API_KEY',
  'GITHUB_APP_ID',
  'GITHUB_APP_PRIVATE_KEY',
  'GITHUB_APP_WEBHOOK_SECRET',
  'ATLASSIAN_CLIENT_ID',
  'ATLASSIAN_CLIENT_SECRET',
  'ATLASSIAN_WEBHOOK_SECRET',
  'SUPABASE_SERVICE_ROLE_KEY',
  'SUPABASE_DATABASE_URL',
  'UPSTASH_REDIS_URL',
  'UPSTASH_REDIS_TOKEN',
] as const;

export interface MergeEnvOptions {
  readonly cwd: string;
  readonly baseline: BaselineEnv;
  readonly force: boolean;
  readonly dryRun: boolean;
}

/**
 * Idempotent merge of the solo-mode sentinels into `<cwd>/.env`:
 * - Existing user-set keys are preserved (Decision 3).
 * - Missing baseline keys are appended.
 * - `--force` overwrites every baseline key with the canonical value
 *   (does not touch user-set keys outside the baseline).
 * - The merged file never includes any of `FORBIDDEN_INIT_KEYS` with a
 *   non-empty value (the secrets-leak invariant per spec §6).
 */
export async function mergeEnvFile(options: MergeEnvOptions): Promise<WriteOutcome> {
  const path = join(options.cwd, '.env');
  const exists = await pathExists(path);
  const baseline = options.baseline as unknown as Record<string, string>;
  const baselineKeys = Object.keys(baseline);

  if (!exists) {
    const lines = [
      '# Generated by `coodra init` per spec §4.1.',
      '# Solo-mode sentinels only — never edit production secrets here.',
      ...baselineKeys.map((key) => `${key}=${baseline[key]}`),
      '',
    ];
    if (!options.dryRun) await writeFile(path, lines.join('\n'), 'utf8');
    return { path, action: 'wrote', notes: 'created baseline .env with solo-mode sentinels' };
  }

  const raw = await readFile(path, 'utf8');
  const lines = raw.split('\n');
  const existingKeys = new Set<string>();
  for (const line of lines) {
    const match = line.match(/^([A-Z_][A-Z0-9_]*)=/);
    if (match?.[1] !== undefined) existingKeys.add(match[1]);
  }

  let mutated = false;

  if (options.force) {
    // Replace lines for baseline keys; append missing ones.
    const updated: string[] = [];
    const written = new Set<string>();
    for (const line of lines) {
      const match = line.match(/^([A-Z_][A-Z0-9_]*)=/);
      const key = match?.[1];
      if (key !== undefined && key in baseline) {
        updated.push(`${key}=${baseline[key]}`);
        written.add(key);
        mutated = true;
      } else {
        updated.push(line);
      }
    }
    for (const key of baselineKeys) {
      if (!written.has(key)) {
        if (updated.length > 0 && updated[updated.length - 1] !== '') updated.push('');
        updated.push(`${key}=${baseline[key]}`);
        mutated = true;
      }
    }
    if (mutated && !options.dryRun) {
      await writeFile(path, updated.join('\n'), 'utf8');
    }
    return {
      path,
      action: mutated ? 'forced' : 'unchanged',
      notes: mutated ? 'rewrote baseline keys to canonical values' : 'baseline keys already canonical',
    };
  }

  // Idempotent merge — only append missing baseline keys; never touch existing user keys.
  const missing = baselineKeys.filter((key) => !existingKeys.has(key));
  if (missing.length === 0) {
    return { path, action: 'unchanged', notes: 'all baseline keys already present' };
  }
  const appended = [
    ...lines,
    '',
    '# Added by `coodra init` (existing values preserved).',
    ...missing.map((key) => `${key}=${baseline[key]}`),
    '',
  ];
  if (!options.dryRun) await writeFile(path, appended.join('\n'), 'utf8');
  return { path, action: 'merged', notes: `added ${missing.length} missing baseline keys` };
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}
