import Link from 'next/link';
import { notFound } from 'next/navigation';

import { GraphReport } from '@/components/graphify/GraphReport';
import { Topbar } from '@/components/Topbar';
import { getGraphifyProjectDetail } from '@/lib/queries/graphify';

export const dynamic = 'force-dynamic';

/**
 * `/graphify/<slug>` — one project's codebase graph.
 *
 * Three panels, in the order a developer actually uses them:
 *   1. the interactive `graph.html` Graphify produced, embedded in a sandboxed
 *      iframe (see `embed/route.ts` for the CSP and why the sandbox omits
 *      `allow-same-origin`);
 *   2. the structural summary derived from `graph.json` — communities by size
 *      and the highest-degree "god nodes", which is the blast-radius signal
 *      §5.6 of the trigger contract tells agents to consult;
 *   3. Graphify's own `GRAPH_REPORT.md`.
 *
 * Nothing here is generated by Coodra, and nothing is fabricated when a file is
 * missing — each panel states plainly that the artifact isn't built yet and
 * names the command that builds it.
 */
export default async function GraphifyProjectPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const result = await getGraphifyProjectDetail(decodeURIComponent(slug));

  if (!result.ok) {
    if (result.reason === 'cloud_hosted') {
      return (
        <>
          <Topbar crumb="Codebase graph" />
          <section className="screen">
            <div className="banner banner--caution">
              <strong>Graphs are local.</strong> This deployment has no repository checkout on disk. Run{' '}
              <Mono>coodra graphify build</Mono> on your own machine.
            </div>
          </section>
        </>
      );
    }
    if (result.reason === 'no_cwd') {
      return (
        <>
          <Topbar crumb="Codebase graph" />
          <section className="screen">
            <div className="banner banner--warn">
              <strong>No recorded project root.</strong> This project row predates the <Mono>cwd</Mono> column, so
              Coodra doesn&rsquo;t know where its files live. Re-run <Mono>coodra init</Mono> from the project
              directory.
            </div>
          </section>
        </>
      );
    }
    notFound();
  }

  const { detail } = result;
  const counts = detail.scan.counts;

  return (
    <>
      <Topbar crumbPrefix="coodra / graph" crumb={detail.slug} />
      <section className="screen">
        <div className="head">
          <div>
            <div className="head__num">/09 · CODEBASE GRAPH</div>
            <h1 className="head__title">{detail.name}</h1>
            <p className="head__lede">
              <span style={{ fontFamily: 'var(--mono)', fontSize: 12 }}>{detail.outputDir}</span>
              {detail.managedByCoodra ? (
                <>
                  {' '}
                  · managed by Coodra (<Mono>GRAPHIFY_OUT</Mono> pinned)
                </>
              ) : (
                <> · Graphify default location (not managed by Coodra)</>
              )}
            </p>
          </div>
          <div className="head__actions">
            <Link href="/graphify" className="btn btn--ghost btn--sm">
              ← all graphs
            </Link>
          </div>
        </div>

        {counts === null ? (
          <div className="empty">
            <strong>
              No graph <em>yet</em>.
            </strong>
            Run <Mono>coodra graphify build</Mono> in <span style={{ fontFamily: 'var(--mono)' }}>{detail.cwd}</span>.
            {detail.scan.countsSkippedReason !== undefined ? (
              <>
                <br />
                <span style={{ color: 'var(--ink-mute)' }}>{detail.scan.countsSkippedReason}</span>
              </>
            ) : null}
          </div>
        ) : (
          <>
            <div className="stats">
              <Stat label="Nodes" value={counts.nodes} />
              <Stat label="Edges" value={counts.links} />
              <Stat label="Communities" value={counts.communities} />
              {/* Compact ("30d", not "30d ago") — the stat number is a large
                  display serif and a two-word value wraps onto the label. */}
              <Stat label="Built" value={detail.builtAt === null ? '—' : formatAge(detail.builtAt)} />
            </div>

            <div className="card" style={{ marginTop: 24 }}>
              <div className="card__head">
                <h2 className="card__title">Interactive graph</h2>
                <span className="card__role">graph.html</span>
              </div>
              {detail.embeddable ? (
                <>
                  {/*
                    sandbox WITHOUT allow-same-origin → opaque origin: the
                    embedded document cannot touch this app's cookies, storage,
                    or DOM. allow-scripts is required because the whole render
                    is vis-network JavaScript.
                  */}
                  <iframe
                    src={`/graphify/${encodeURIComponent(detail.slug)}/embed`}
                    title={`Graphify codebase graph for ${detail.name}`}
                    sandbox="allow-scripts"
                    referrerPolicy="no-referrer"
                    style={{
                      width: '100%',
                      height: 620,
                      border: '1px solid var(--rule)',
                      borderRadius: 8,
                      background: '#0f0f1a',
                      display: 'block',
                    }}
                  />
                  <p style={{ fontSize: 12, color: 'var(--ink-mute)', margin: '10px 0 0' }}>
                    Graphify&rsquo;s viewer loads <Mono>vis-network</Mono> from unpkg with an SRI integrity hash — the
                    canvas stays blank if this machine is offline. Everything below is read from <Mono>graph.json</Mono>{' '}
                    and works offline.
                  </p>
                </>
              ) : (
                <p style={{ fontSize: 13, color: 'var(--ink-mute)', margin: 0 }}>
                  No <Mono>graph.html</Mono> in the output directory (or it resolves outside the project root, which
                  Coodra refuses to serve). Rebuild with <Mono>coodra graphify build</Mono>, or open it directly with{' '}
                  <Mono>coodra graphify open</Mono>.
                </p>
              )}
            </div>

            {detail.summary !== null ? (
              <div className="dash-grid" style={{ marginTop: 24 }}>
                <div className="card">
                  <div className="card__head">
                    <h2 className="card__title">Communities</h2>
                    <span className="card__role">largest first</span>
                  </div>
                  {detail.summary.communities.length === 0 ? (
                    <p style={{ fontSize: 13, color: 'var(--ink-mute)', margin: 0 }}>
                      No community assignments in this graph.
                    </p>
                  ) : (
                    <div className="dash-list">
                      {detail.summary.communities.map((c) => (
                        <div key={c.id} className="row">
                          <div className="row__main">
                            <div className="row__title">Community {c.id}</div>
                            <div className="row__sub">{c.sampleLabels.join(' · ')}</div>
                          </div>
                          <div className="row__time">
                            {c.size} node{c.size === 1 ? '' : 's'}
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                <div className="card">
                  <div className="card__head">
                    <h2 className="card__title">God nodes</h2>
                    <span className="card__role">most connected</span>
                  </div>
                  {detail.summary.hubs.length === 0 ? (
                    <p style={{ fontSize: 13, color: 'var(--ink-mute)', margin: 0 }}>No edges in this graph.</p>
                  ) : (
                    <div className="dash-list">
                      {detail.summary.hubs.map((h) => (
                        <div key={h.id} className="row">
                          <div className="row__main">
                            <div className="row__title">{h.label}</div>
                            <div className="row__sub">{h.sourceFile ?? h.id}</div>
                          </div>
                          <div className="row__time">
                            {h.degree} edge{h.degree === 1 ? '' : 's'}
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            ) : null}
          </>
        )}

        {detail.report !== null ? (
          <div className="card" style={{ marginTop: 24 }}>
            {/*
              Collapsed by default. Graphify's report scales with community
              count: vigil's 435 communities produce a 170 KB report that
              rendered a 50,000-pixel page, burying the graph and the summary
              above it. A <details> keeps the report one click away without
              costing the rest of the page its navigability.
            */}
            <details>
              <summary style={{ cursor: 'pointer', listStyle: 'revert' }}>
                <span className="card__title" style={{ display: 'inline' }}>
                  Graph report
                </span>{' '}
                <span className="card__role">GRAPH_REPORT.md · {formatBytes(detail.report.length)}</span>
              </summary>
              <div style={{ marginTop: 18 }}>
                <GraphReport markdown={detail.report} />
                {detail.reportTruncated ? (
                  <p style={{ fontSize: 12, color: 'var(--ink-mute)', marginTop: 12 }}>
                    Report truncated for display — read the full file at{' '}
                    <span style={{ fontFamily: 'var(--mono)' }}>{detail.scan.paths.report}</span>.
                  </p>
                ) : null}
              </div>
            </details>
          </div>
        ) : null}
      </section>
    </>
  );
}

function Stat({ label, value }: { readonly label: string; readonly value: string | number }) {
  return (
    <div className="stat">
      <div className="stat__num">{value}</div>
      <div className="stat__label">{label}</div>
    </div>
  );
}

function Mono({ children }: { readonly children: React.ReactNode }) {
  return <span style={{ fontFamily: 'var(--mono)', color: 'var(--accent)' }}>{children}</span>;
}

/** Single-token age ("2h", "30d") — fits the display-serif stat on one line. */
function formatAge(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  if (Number.isNaN(diff)) return '—';
  if (diff < 3_600_000) return `${Math.max(1, Math.floor(diff / 60_000))}m`;
  if (diff < 86_400_000) return `${Math.floor(diff / 3_600_000)}h`;
  return `${Math.floor(diff / 86_400_000)}d`;
}

function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${Math.round(n / 1024)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}
